# Generated by Django 3.1.1 on 2020-10-27 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NN_layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer1', models.PositiveSmallIntegerField(default=64)),
                ('layer2', models.PositiveSmallIntegerField(default=64)),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('loss_train', models.CharField(default=0, max_length=10)),
                ('loss_test', models.CharField(default=0, max_length=10)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='selectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('data', models.FileField(null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator('.csv', 'csvファイル以外は使えません。すみません。')])),
            ],
        ),
        migrations.CreateModel(
            name='selectedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
            ],
        ),
    ]
